[package]
name = "ethlambda-crypto"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
ethlambda-types.workspace = true

lean-multisig = { git = "https://github.com/qdrvm/leanMultisig.git", rev = "b030a846798ab950fb711997120f05041650d88d" }
# leansig_wrapper provides XmssPublicKey/XmssSignature types used by lean-multisig's public API
leansig_wrapper = { git = "https://github.com/qdrvm/leanMultisig.git", rev = "b030a846798ab950fb711997120f05041650d88d" }

leansig.workspace = true
thiserror.workspace = true
rand.workspace = true

[dev-dependencies]
hex.workspace = true
